version: '3.8'
services:
  LisiorCrea:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - LSCR
  test-db:
    image: postgres:13
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - LSCR
networks:
  LSCR:
    external: true
